import Head from "next/head";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { addToCart } from "@/slices/cartSlice";
import { getProducts } from "@/slices/productsSlice";
import { product, stateType } from "@/types";
import Products from "@/components/Products/Products";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const navigate = useRouter();
    const dispatch = useDispatch();

    const handleAddToCart = (product: product) => {
        dispatch(addToCart(product));
        navigate.push("/cart");
    };

    const products = useSelector((state: stateType) => {
        return state.products.products;
    });
    useEffect(() => {
        dispatch(getProducts());
    }, [dispatch]);

    const Container = styled.div`
        padding: 2rem 4rem;
        h2 {
            font-size: 40px;
            font-weight: 400;
            text-align: center;
        }
    `;

    const Items = styled.div`
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
        margin-top: 2rem;
    `;

    return (
        <>
            <Head>
                <title>React Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <Container>
                <>
                    <h2>Our products</h2>
                    <Items>
                        {products?.map((product: product) => (
                            <div key={product.id}>
                                <Products
                                    handleAddToCart={handleAddToCart}
                                    product={product}
                                />
                            </div>
                        ))}
                    </Items>
                </>
            </Container>
        </>
    );
}
