import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { addToCart } from "@/slices/cartSlice";
import { getProducts } from "@/slices/productsSlice";
import { product, stateType } from "@/types";
import styles from "@/styles/Home.module.css";
import Products from "@/components/Products/Products";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const navigate = useRouter();
    const dispatch = useDispatch();

    const handleAddToCart = (product: product) => {
        dispatch(addToCart(product));
        navigate.push("/cart");
    };

    const products = useSelector((state: stateType) => {
        return state.products.products;
    });
    useEffect(() => {
        dispatch(getProducts());
    }, [dispatch]);

    return (
        <>
            <Head>
                <title>React Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <div className={styles.container}>
                <>
                    <h2>Our products</h2>
                    <div className={styles.items}>
                        {products?.map((product: product) => (
                            <div key={product.id}>
                                <Products
                                    handleAddToCart={handleAddToCart}
                                    product={product}
                                />
                            </div>
                        ))}
                    </div>
                </>
            </div>
        </>
    );
}
